### ISSUE TITLE
请大家多交流翻墙，让免费翻墙更容易

### ISSUE THREAD

**Issue by hugetiny** [hugetiny/awesome-vpn#10]
在中国，官二代红二代富二代几乎都移了民或者移民中，爱国是穷人的专利，然而穷人是真的爱国吗？我想起胡适的一句话：
“中国人从来不爱中国人，爱人是需要投入情感，付出时间精力、经济成本的，爱国只需要付出口水...”
网上喷喷口水很简单，要冒点危险让喷子去抗枪上阵估计没几个继续装什么爱国。

现在很多人被洗脑了爱共产党===爱国这个概念
if 你爱共产党，请不要翻墙，遵从党的意志，不要让党的工作白费了
else if 你爱国，请帮助中国更自由，最起码更自由的上网吧，这个实在点
else if 你觉得中国足够自由了，宪法貌似允许普通人随便上网，随便讲话，当然中国人都知道宪法也是张废纸。

所以翻墙就翻墙，少给我废话什么爱国不爱国。爱共产党就不要翻墙。

**Comment by longwusha** [comment]
通信自由与免费翻墙更容易这一点上，没太多人有什么反对意见。大家反对的是你借此机会说的一些不和时宜的话和做的不合时宜的事。

言论自由不是你用来伤害他人，伤害国家主权和领土完整的借口。你们这些人，只会口头谈自由，不理解自由与法制的边界，不理解自由是以相互尊重为前提。在你们的心中，自由与反对是绑定的。不会反对的就是不自由的？先睁开你的眼睛看清楚你反对的东西是什么，你反对的东西的缘由经过结果是什么，不然你就不是一个“自由”的人，而是一个没有脑子的人。

你也不用在这装无辜，说什么“欢迎骂我”，用你自己的话说，这是我们的言论自由，这是你活该遭受的。这也是我们会攻击你们的另一个原因，当你们自己用言论自由为借口来伤害14亿中国人民的感情的时候，当你们肆意践踏侮辱中国的主权和领土完整的时候，竟然觉得自己是正义凛然的；反过来我们对你说些什么的时候，你却觉得自己多么的无辜，我们是多么的错误和愚蠢。能有这种想法的人，是该有多么的愚蠢和傲慢，双标狗，不外如是！

最后，作为一个中国人，严正的再强调一遍：请尽快撤回仓库文件中涉及中国香港的错误言论！！！

**Comment by longwusha** [comment]
爱共产党===爱国  这一点用不着你来指指点点，我们有自己的判断。至少我们知道  爱国 !=分裂国土，我们知道  爱国 !=违法犯罪。

**Comment by longwusha** [comment]
看到你引用了胡适的一句话：
“中国人从来不爱中国人，爱人是需要投入情感，付出时间精力、经济成本的，爱国只需要付出口水...”

我真的不知道你过没过脑子思考过这句话，你有没有想过胡适所在的那个时代，有多少人为了中国的独立自主和繁荣昌盛抛头颅洒热血，流尽了血和汗。

知道胡适这位所谓的名人为什么会说出这么愚蠢的话吗？因为他跟你一样，没好好想过自己为爱国要做些什么能做些什么，没有睁开眼睛看看别人是怎么爱国的；因为别人在自己的工作岗位上为建设强大的中国尽自己的微薄之力的时候，你们却只会在那侮辱和践踏中国。

爱国两字，好好想一想，你们自己现在在做的事，你配提吗？

**Comment by hugetiny** [comment]
废话一大堆，解释的很清楚了。你翻墙违法犯罪了啊，爱国的你干嘛不去自首啊
