### ISSUE TITLE
先说结论：你==猪

### ISSUE THREAD

**Issue by lifuzhao100** [hugetiny/awesome-vpn#13]
你==吃饭+睡觉
猪==吃饭+睡觉
so 你==猪？！
神他妈的脑回路 爱党==爱国，爱国就不能翻墙？
我爱的和平稳定，不受他国欺辱的国家，而恰巧这个执政者是共产党，如果今天执政的台湾的民进党，（哦，不好意思，举错例子，这个傻逼政党只会当别人的干儿子，媚美媚日，耻辱），只要能为它的人民提供和平稳定的生活条件，我们就拥护它！！！
香港独立是不可能的，不信就走着瞧？加油，希望你能活着看到香港独立。答应我，一定要活着看到这一刻。

**Comment by hugetiny** [comment]
什么狗屁不通的例子，莫名其妙，你热爱共产党管我屁事
