### ISSUE TITLE
港剧将要大团圆结局？

### ISSUE THREAD

**Issue by YoungHongkongTrash** [hugetiny/awesome-vpn#14]
https://weibo.com/1897923205/IgHCu2Ays?ref=feedsdk&type=comment#_loginLayer_1574056866645
我希望你们不要那么快大结局，我真的还想下班后看看你们这些蚍蜉奋斗
感谢你们这半年来无私奉献的精彩大剧
23333333333333333333333333333
我真的还想再看看你们，每四五年来一段真的不过瘾，最好每年来一回，一回玩足12个月

**Comment by hugetiny** [comment]
不太清楚啊，纠正你一个错误，不是“你们”，我不是香港人。
