### ISSUE TITLE
issue仅供翻墙交流

### ISSUE THREAD

**Issue by hugetiny** [hugetiny/awesome-vpn#15]
一些五毛莫名其妙老是issue扯什么美国爸爸之类的，在中国翻个墙，关美国屁事。

还有一些五毛会扯到共产党多好，你爱共产党你去别地方歌颂去，这里提供翻墙交流，你爱共产党你就别翻墙。党和方滨兴A了好多纳税人的钱才建起的墙你怎么可以随便的翻过！你们真是对党辛苦为民众建立绿色网络环境的亵渎啊！抓起来。

类似的话不想说了，以后来一个五毛封一个，五毛说我支持言论自由就应该让你自由在我个人repo的issues里面喷垃圾那是五毛自己的逻辑有问题。

**Comment by bigJiaLuo** [comment]
支持，一些人真的很过分

**Comment by shusim** [comment]
原来用SS，现在切到了SSR，感觉方便了一点点

**Comment by hugetiny** [comment]
> 原来用SS，现在切到了SSR，感觉方便了一点点

感觉SSR的都很慢，SSR现在有没有一个在维护repo，我看到的都是停止维护的

**Comment by SteinsHead** [comment]
感觉V2ray还不错，主要是墙管的很严

**Comment by zxj121188** [comment]
最近V2ray不稳定啊，想访问youtube有点难啊

**Comment by zxj121188** [comment]
> 感觉V2ray还不错，主要是墙管的很严

最近V2ray似乎不行啊，无法满足u2b的需要

**Comment by hugetiny** [comment]
V2ray官方客户端貌似还不支持负载均衡，如果是支持的话 不管快慢，应该总有几个能上的。现在只能手动测速试试上

**Comment by zxj121188** [comment]
> V2ray官方客户端貌似还不支持负载均衡，如果是支持的话 不管快慢，应该总有几个能上的。现在只能手动测速试试上

我对网络编程不是很了解。大佬您推荐的那些vpn哪个比较能满足看YouTube视频需要？

**Comment by ljn666666** [comment]
V2ray似乎不能用了

**Comment by AnyWAT** [comment]
看YouTube视频，貌似迷雾通Windows、安卓（及其它？）版尚可

**Comment by hugetiny** [comment]
不要发广告，只接受免费vpn的交流

**Comment by AnyWAT** [comment]
貌似被推介的 lantern 与 XX-Net 也都有（除免费外的）付费部分，与。。。纯用户被删除的“广告”有何异同？
![image](https://user-images.githubusercontent.com/37962734/80083290-07bb8e00-8588-11ea-92f3-f216a8e8d77a.png)

**Comment by AnyWAT** [comment]
曾经、正在只使用 lantern 与 XX-Net 的免费部分的蠢用户一枚🤣

**Comment by qmwneb008** [comment]
真尼玛垃圾，逛github都能遇到你这种恶心人

**Comment by jeerychris** [comment]
节点今天都不能用了吗

**Comment by jeerychris** [comment]
配置里面隐藏的url, 是大佬配置的。那evernote有人看过没, 里面的东西可靠吗

**Comment by hugetiny** [comment]
> 配置里面隐藏的url, 是大佬配置的。那evernote有人看过没, 里面的东西可靠吗

你应该说是客户端下载链接吧？
都是官方repo的github release最新链接。初衷就是为了方便下载。
不放心的话可以鼠标停留在每一个地址上面查看。
手机浏览器一般是长按复制链接地址到地址栏查看。

**Comment by CodeJasmine** [comment]
现在梯子还能用嘛，我咋打不开😂

**Comment by dodois** [comment]
可以试试这个 https://github.com/dodois/dosvpn

**Comment by dingsahnghuafo** [comment]
现在的梯子哪个可以用呢？手机安卓的

**Comment by qhq** [comment]
> 现在的梯子哪个可以用呢？手机安卓的
试试这个，速度不错
https://www.20hlir025.space?userid=WWIEH4&t=1876 请复制链接到系统浏览器打开
