### ISSUE TITLE
调查：你所在的地区github release下载慢吗？

### ISSUE THREAD

**Issue by hugetiny** [hugetiny/awesome-vpn#18]
应该是CDN部分被屏蔽导致的，如果有现有代理。请用代理下载

**Comment by chinazyq123** [comment]
Quite slow



在 2020-03-07 20:01:27，"Neginegi" <notifications@github.com> 写道：

**Comment by SteinsHead** [comment]
下载真的很慢，吐了

**Comment by zxj121188** [comment]
V2ray 批量导入URL似乎不行啊！大佬的教程能不能详细点

**Comment by hugetiny** [comment]
@zxj121188  已经更新复制粘贴无效时的方法

**Comment by hugetiny** [comment]
貌似最近github越来越难上，以后可能要挂着代理才能用github了

**Comment by ljn666666** [comment]
V2RAY 不能用了
