### ISSUE TITLE
这个项目只接受免费开源的VPN分享

### ISSUE THREAD

**Issue by hugetiny** [hugetiny/awesome-vpn#32]
项目很久没有更新了，不知道为啥星还在涨，很多人还来发广告。
这些年我的一些想法有变化，没有PR只有喷子喷我，我也懒得更新，这个项目就做纯免费开源的VPN分享。
那种免费试用的盈利为目的项目就不要在我这发广告了。

**Comment by yangyibiao** [comment]
unsubscribe&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Jun 2, 2022 10:17 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;Re: [hugetiny/awesome-vpn] 这个项目只接受免费开源的VPN分享 (#32)

&nbsp;
 Closed #32 as completed.
