### ISSUE TITLE
作爲一個中國人我真以你爲恥！

### ISSUE THREAD

**Issue by Caponia** [hugetiny/awesome-vpn#5]

**Comment by zry2002** [comment]
美国人民处于水深火热之中，的确需要你们这些狂热分子去支持华盛顿独立。去美国吧！不要来扰乱我们国家的安宁！不要低估我们国家人民捍卫自己生存、发展和追求幸福的权利的决心！香港永远是中国的一部分，台湾永远是中国的一部分！
自由美利坚，枪击每一天！要能躲得过，来支电子烟 ！

**Comment by zry2002** [comment]
这个developer到处删评论，这就是你的自由？你的民主呢？
一切暴徒都是跳梁小丑！
中国共产党在为10亿人脱贫，你们连800万人的好日子也要去打破！
我看不出那些满口freedom的人，在手持燃烧瓶，打砸基建设施，殴打普通市民，焚毁各种商铺，破坏高校秩序，扰乱香港经济，就是为了他美国爷爷的一点点施舍上，与那些731部队的日本人，奥斯维辛的纳粹兵，有什么本质上的区别。
孩子，劝你一句，别把祖国的宽容，当成了纵容！
别人爱不爱国爱不爱党我不知道，但是你这个“fight for freedom”的人，是个彻头彻尾的碍国者，碍党者，碍港者！

**Comment by zry2002** [comment]
你有本事就别删评，让大家看看，你的真实用心！

**Comment by hugetiny** [comment]
五毛键盘，奴才当太久站不起来了

**Comment by hugetiny** [comment]
五毛键盘，奴才当太久站不起来了

**Comment by hugetiny** [comment]
莫名其妙扯到美国，跟美国有毛关系，被洗脑的奴才，只会在键盘上喷
