### ISSUE TITLE
傻逼

### ISSUE THREAD

**Issue by vincent931018** [hugetiny/awesome-vpn#7]
HK is a part of china！
Do you know？
son of bitch！

**Comment by longwusha** [comment]
靠，你不说，我都没注意到首页改了

**Comment by longwusha** [comment]
Hong Kong is part of China and no one can separate it. Anyone with this intention will pay a painful price.

**Comment by hugetiny** [comment]
一堆脑残，就知道喷
谁说不是中国一部分了
